[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

  [[http_service.checks]]
    interval = "5s"
    timeout  = "2s"
    method   = "GET"
    path     = "/health"
