app = "dpa-fly-backend-twilio"
primary_region = "syd"

[deploy]
  release_command = ""
  strategy = "immediate"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false    # ✅ Don't stop machines automatically
  auto_start_machines = true
  min_machines_running = 1      # ✅ Keep one machine always running
  processes = ["app"]

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.http_checks]]
    method = "get"
    path = "/"
    protocol = "http"

  [services.tls_options]
    alpn = ["h2", "http/1.1"]
    versions = ["TLSv1.3", "TLSv1.2"]
