app = "dpa-fly-backend-twilio"
primary_region = "syd"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [http_service.tls_options]
    # Ensure both TLS 1.3 and 1.2 are allowed (Twilio uses either)
    versions = ["TLSv1.3", "TLSv1.2"]
